version: "3.3"
services:
  app:
    container_name: flask_app
    build: .
    restart: unless-stopped
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_PORT=5000
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8000:5000"
    volumes:
      - ./:/app
    command: python run.py